services:
  - type: web
    name: crypto-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: crypto-db
          property: host

      - key: DB_NAME
        fromDatabase:
          name: crypto-db
          property: database

      - key: DB_USER
        fromDatabase:
          name: crypto-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: crypto-db
          property: password

      - key: DB_PORT
        fromDatabase:
          name: crypto-db
          property: port

  - type: cron
    name: crypto-etl
    env: python
    buildCommand: pip install -r requirements.txt
    schedule: "*/5 * * * *"
    startCommand: python etl_pipeline.py

databases:
  - name: crypto-db